# Navigation Links
#   To link a page section, specify the URL as a hash `/#` followed by the `id` of the section.
#   The `weight` parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /#top
    weight: 10
  - name: Vision
    url: /#vision
    weight: 20
  - name: Up Next
    url: /#progress
    weight: 30
  - name: Contact Us
    url: /#contact-details
  # - name: Resources
  #   weight: 40
  #   hasChildren: true
  # - parent: Resources
  #   name: Blog
  #   url: blog/
